version: '3.7'
networks:
  testnetwork:
          driver: bridge 
services:
  postgres12:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    networks:
      - testnetwork
    environment:
      - POSTGRES_DB=BankDB
      - POSTGRES_PASSWORD=reto
  test-neorios:
    image: test-neorios:v1
    ports:
      - "8082:8082"
    restart: always
    networks:
      - testnetwork
    depends_on:
      - postgres12
